A small refactor of lcu.py
SecreSwalowtail/League-of-Legends-Lobby-Shower-GUI pull request #2
Opened 2022-12-21 11:21 UTC by ZefyrCz

2022-12-22 15:58 UTC, SecreSwalowtail requested changes
participant_names.update method does not return anything so we get a None TypeError

2022-12-22 21:00 UTC, ZefyrCz commented
True, didn't realize :)

2022-12-23 00:08 UTC, SecreSwalowtail approved these changes

2022-12-23 00:11 UTC, SecreSwalowtail approved these changes

2022-12-23 00:12 UTC, merged